development:
  host: localhost
  database: skills_tradr_development

test:
  host: localhost
  database: skills_tradr_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['mongodb://heroku_app4194561:98u3u8csq3fth4pdpbmhs4d5qp@ds029277.mongolab.com:29277/heroku_app4194561'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
